#Exercicio4:Faça um Programa que peça as 4 notas bimestrais e mostre a média.
print('MÉDIA BIMESTRAL')
print()
print()
n1 = float(input('Informe a primeira nota: '))
n2 = float(input('Informe a segunda nota: '))
n3 = float(input('Informe a terceira nota: '))
n4 = float(input('Informe a quarta nota: '))
print()
media = ((n1 + n2 + n3 +n4) / 4)
print(f'Sua média foi {media}')
